ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS status VARCHAR(20);

UPDATE accounts
SET status='ACTIVE'
WHERE status IS NULL;

ALTER TABLE accounts
ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE accounts
ALTER COLUMN status SET NOT NULL;